### PR TITLE
Adds support for syncing deal pipelines

### PR DESCRIPTION
**Pull request by jaeger401**
Please let me know if anything need to be adjusted in this -- deal pipelines don't have any timestamps on them, so they don't appear to have a precedent among the other data currently supported by this tap. I took a shot at what I think would be the best approach. Thanks!

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @jaeger401, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @jaeger401!

Thank you for signing the Singer Contribution License Agreement.

**Comment by psantacl** [comment]
It looks like the deal_pipeline schema you provide is malformed at the declaration of the stages array.  A json schem validator I found online produced the following notes:

```
[ {
  "level" : "warning",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : "/properties/stages/items"
  },
  "domain" : "syntax",
  "message" : "the following keywords are unknown and will be ignored: [active, closedWon, displayOrder, label, probability, stageId]",
  "ignored" : [ "active", "closedWon", "displayOrder", "label", "probability", "stageId" ]
} ]
```

**Comment by psantacl** [comment]
Please run this new code along with the target in the dry-run mode to verify the schema emits the data you are looking for.  If you need help running the target alongside the tap, please ask around in slack.

**Comment by jaeger401** [comment]
I have corrected the schema (complicated by the fact that the first online validator I used found no issues), added an undocumented field, and corrected a typo. Piping this tap into `target-csv` produces results that appear to be sane. Care to have a second look, @psantacl?

**Comment by psantacl** [comment]
merged and released

**Pull request closed without merging**
